### ISSUE TITLE
ToDo | Detector Simulation

### ISSUE THREAD

**Issue by sagitta42** [legend-exp/LegendGeSim.jl#34]
ToDo items related to detector simulation

- [ ] Figure out where to input dead layer. Currently as a quickfix for my studies it's in `Environment` which is opposite of elegant. Implement settings that mean "as default take vendor value", "as default take L200 char value", or take provided value or zero as default. TBD
- [x] test what happens if medium is LAr - never tested so far. Also, `"temperature"` might be optional because correlated to medium.

Fieldgen related
- [ ] Save estimated depV from fieldgen simulation into variable, similar to how capacitance is treated, in order to be able to access it for a table, plotting etc. Tommaso said it's, quote, "annoying in siggen, harder than capacitance". Will keep in touch
- [x] Generate siggen `.spe/.dat` unformatted Float32 impurity profile files on the fly based on crystal metadata to then input to fieldgen. Currently only option is give path to existing `.spe` file
- [ ] does `"medium"` variable do anything
- [ ] super low priority - do some sort of `OrderedDict` for siggen config file - the resulting fieldgen config file has parameters in chaotic order, hard to read and compare
