### ISSUE TITLE
ToDo | General

### ISSUE THREAD

**Issue by sagitta42** [legend-exp/LegendGeSim.jl#37]
ToDo items that span several stages from detector to elec response simulation

- [x] try to process `raw` file with pygama -> actually first check if the format is still the same, this is format from 2 years ago
- [ ] Currently have `overwrite` as input for detector simulation (overwrite SSD hdf5 or fieldgen WP and EP files) -> implement also for `simulate_pulses` and `simulate_waveforms`, maybe call "overwrite_det_sim" or something like that to not be confused with caching waveforms themselves
- [x] Add more tests
- [x] Add Tutorial notebook to repo
- [ ] docstrings
- [ ] Currently caching detector simulation only if cached name provided -> should do the same for pss and raw? stp? Or user can cache their table by themselves? -> currently `simulate_waveforms` can read cached `pss` file, but `pss` does not start from `stp`, only from `pet` -> think of caching in general, how to organize
- [x] Test on non-ICPC
- [ ] Want `@info` to not say which line/module it prints from to avoid log clutter
- [ ] Optional detector metadata in json config (currently only separate input) to have one config that contains all info. Convenient to save and document exactly with what input something was simulated. More convenient to have detector separate from env, sim and setup settings for looping purposes. Therefore should be optional input syntax.
- [ ] If cached name given no need for other detector simulation related settings! Right now first announces the settings, then just says cached sim is being read, so all of those settings are irrelevant. Also impossible to make sure what settings were used reading from cached sim - cached name chosen by user, not required to mention settings there. Hypothetically probably settings are recoverable (e.g. can see impurity gradient, voltage, but maybe not DL)
- [ ] {T} in Preamp etc -> @oschulz @fhagemann we should call and you explain to me what this `T` stuff is, why it's good, and some rule of thumb on what to do there

**Comment by sagitta42** [comment]
@oschulz @fhagemann a small question: advice on how to name an optional bool variable in `simulate_pulses()` and `simulate_waveforms()` that corresponds to `overwrite` in `simulate_fields()` i.e. determines whether to read cached simulation if present with given cached name or overwrite it. I'm thinking simply `overwrite` could be ambiguous  when talking about waveform simulation (even though the only thing written is always only detector simulation). So maybe something like `overwrite_fields`?

Then it would look something like this:

```julia
pss_table, pss_truth = LegendGeSim.simulate_pulses(detector_metadata_filename, pet_input_file,
    environment_settings, simulation_settings, noise_model; n_waveforms=100, overwrite_fields=true)
```

**Comment by oschulz** [comment]
Which of the arguments of `simulate_pulses` contains data that would be overwritten?

**Comment by sagitta42** [comment]
Nothing "contains" data that should be overwritten. The argument `overwrite` should be passed to `stp_to_pss()` in `simulate_pulses()` where it would then be passed to `simulate_detector()`. Currently in `stp_to_pss()` the function `simulate_detector()` is called with a hard-coded `overwrite = false`.

https://github.com/legend-exp/LegendGeSim.jl/blob/249a22280d728ce059c32e1e679dcbf70b806330/src/stp_to_pss.jl#L19

**Comment by fhagemann** [comment]
How about, in general, using `recalculate` (or `recalculate_fields`) rather than `overwrite` (or `overwrite_fields`)?

**Comment by sagitta42** [comment]
I like it! Maybe some how include the word "cached" in the variable, e.g. `overwrite_cached` to refer to the "cached name" in the simulation settings. That could be intuitive. The most descriptive and accurate name would be `recalculate_cached_fields`, but do we want an optional variable name be that long...

**Comment by oschulz** [comment]
Makes sense.

**Comment by fhagemann** [comment]
Question is: what exactly does the keyword do?

I feel like there might be three options which might be wanted by the user:
* calculate the fields but discard them at the end of the simulation without saving them
* calculate the fields and save them to the cache (file)
* load the fields from the cache (file)

We might need two keywords for this, something like `save_fields` and `load_cached_fields`?
Or is any of the three scenarios never the case? Then, we might be able to work with one keyword argument and can be fixed according to what we actually select.

**Comment by sagitta42** [comment]
This keyword controls whether to read cached simulation from file based on given cached name or overwrite it.

Option 1 is achieved by not providing a cached name in the simulation, then it doesn't matter what `overwrite` is.

Option 2 calculate the fields and cache them to a file - currently done if file does not exist yet; if it exists, the fields will be read unless `overwrite` is `true` (= option 3)
