### ISSUE TITLE
ToDo | noise model

### ISSUE THREAD

**Issue by sagitta42** [legend-exp/LegendGeSim.jl#61]
- [ ] update baseline selection: instead of the HADES version wtih extracting baseline from the waveform that contains signal (so just the short chunk before it's rising), it has to be replaced with selecting waveforms from L200 phy data that are all flat baselines. Currently in `baselines.jl` in the main function `baseline_catalog()`, a baseline is selected via `selection_cut()`, should create a new function that simply tags the whole waveform as baseline and adds that to the catalog
- [ ] update baseline adding: currently since HADES "baselines" in the catalog are shorter than the full waveform, in `noise.jl` in `simulate_noise(wf::RDWaveform, noise_model::NoiseFromData)`,  a function `extend_baseline()` is called. This line simply needs to be removed as L200 baselines are already exactly the number of samples that they need to be (if the FADC settings in LegendGeSim were set properly to correspond to the data from which the baselines are extracted)
- [ ] currently if `NoiseFromData` is selected, fano noise is not simulated. Is that how it's supposed to be? Does the baseline itself already contain the effects of the fano noise? It seems that it's only electronics noise (since no actual signal was registered, so there's no germanium crystal effect on anything). In this case, this needs to be fixed to bring back fano noise into the simulation even when `NoiseFromData` model is selected. Would need to change the ` fano_noise(events::Table, ::PropDict, ::Environment, ::NoiseFromData)` function which enforces skipping fano noise in case of noise from data. What should then happen is that the actual `fano_noise()` function that adds it should take as input `::Union{NoiseFromSim, NoiseFromData}` or something like that
